user_name = input("Введите имя пользователя: ")
title = input("Заголовок : ")
content = input("Описание: ")
status = input("Статус работы: ")
created_date = input("Начало работы (дд.мм.гг.): ")
issue_date = input("Окончание работы (дд.мм.гг.): ")
print ("Здравствуйте,", (user_name))
print("Ваша тема:", (title))
print("Описание:",(content))
print("Статус работы:", (status))
print("Дата начала:", (created_date))
print("Дата окончани:", (issue_date))
tuple_1= user_name, 'Ваша тема:', title, 'Описание: ', content,'статус работы:', status, 'Дата начала:', created_date, 'Дата окончани:', issue_date
user_name = input("Введите имя пользователя: ")
title = input("Заголовок : ")
content = input("Описание: ")
status = input("Статус работы: ")
created_date = input("Начало работы (дд.мм.гг.): ")
issue_date = input("Окончание работы (дд.мм.гг.): ")
print("Ваша тема:", (title))
print("Описание:",(content))
print("Статус работы:", (status))
print("Дата начала:", (created_date))
print("Дата окончани:", (issue_date))
tuple_2=user_name, 'Ваша тема:', title, 'Описание: ', content,'статус работы:', status, 'Дата начала:', created_date, 'Дата окончани:', issue_date
print(tuple_1[0:])
print(tuple_2[0:])